[project]
name = "analizer-constitution"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "langchain[openai]>=0.3.27",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
